Repository lf-edge/eve, pull requests merged in 2023-10, with the labels that each got.

#3470 [10.4 stable] agentlog: fix dumping stacks locally
  pkg/pillar/agentlog/agentlog.go
Labels: bug

#3490 zedrouter: fix hosts file with multiple IPs assigned to the same hostname
  pkg/pillar/nireconciler/genericitems/dnsmasq.go
  pkg/pillar/nireconciler/genericitems/dnsmasq_test.go
  pkg/pillar/nireconciler/linux_config.go
  pkg/pillar/nireconciler/linux_test.go
Labels: bug, stable

#3509 diskmetrics: increase timeout of qemu img convert
  pkg/pillar/diskmetrics/diskmetrics.go
Labels: stable

#3540 Revert "Makefile: Workaround to fix QEMU's MSR errors"
  Makefile
Labels: stable
