Repository lf-edge/eve, pull requests merged in 2024-09, with the labels that each got.

#4193 dpcreconciler: set MAC and interface rename while interface is DOWN
  pkg/pillar/dpcreconciler/linuxitems/adapter.go
Labels: bug

#4228 Cleanup /persist/pubsub-large on boot
  pkg/pillar/pubsub/socketdriver/publish.go
  pkg/pillar/scripts/onboot.sh
Labels: stable

#4237 Blacklist wdat_wdt for Siemens IPC227G
  pkg/grub/rootfs.cfg
Labels: stable

#4251 vTPM : fix arm issue by selecting correct dev name based on arch
  pkg/pillar/hypervisor/kvm.go
Labels: bug

#4238 pillar/assignableadapters: clear error strings
  pkg/pillar/cmd/domainmgr/domainmgr.go
  pkg/pillar/cmd/zedagent/reportinfo.go
  pkg/pillar/types/assignableadapters.go
  pkg/pillar/types/assignableadapters_test.go
Labels: stable

#4253 Enhance LinuxCollector to support detecting multiple app VIF IPs
  docs/APP-CONNECTIVITY.md
  docs/CONFIG-PROPERTIES.md
  pkg/pillar/cmd/msrv/msrv_test.go
  pkg/pillar/cmd/msrv/pubsub.go
  pkg/pillar/cmd/zedagent/handleconfig.go
  pkg/pillar/cmd/zedagent/handlemetrics.go
  pkg/pillar/cmd/zedagent/handlenetworkinstance.go
  pkg/pillar/cmd/zedrouter/appnetwork.go
  pkg/pillar/cmd/zedrouter/ipam.go
  pkg/pillar/cmd/zedrouter/networkinstance.go
  pkg/pillar/cmd/zedrouter/pubsubhandlers.go
  pkg/pillar/cmd/zedrouter/zedrouter.go
  pkg/pillar/nistate/linux.go
  pkg/pillar/nistate/linux_dnsmasq.go
  pkg/pillar/nistate/linux_flow.go
  pkg/pillar/nistate/linux_iptables.go
  pkg/pillar/nistate/statecollector.go
  pkg/pillar/pubsub/memdriver_test.go
  pkg/pillar/types/zedroutertypes.go
Labels: stable

#4259 Kernel update - [arm64-nvidia, arm64-nvidia, arm64-generic]
  kernel-commits.mk
Labels: bug

#4267 Properly initialize AppNetworkStatus after invalid config was fixed
  pkg/pillar/cmd/zedrouter/appnetwork.go
  pkg/pillar/cmd/zedrouter/pubsubhandlers.go
Labels: bug, stable

#4270 vtpm fix : use domain uuid instead of full domain name
  pkg/pillar/hypervisor/kvm.go
Labels: bug

#4277 installer: Find persist partition when installing into another disk
  pkg/installer/install
Labels: bug, stable

#4295 pkg/pillar: make ioBundleError deepcopy-able
  pkg/pillar/pubsub/publish.go
  pkg/pillar/pubsub/subscribe.go
  pkg/pillar/pubsub/util.go
  pkg/pillar/pubsub/util_test.go
  pkg/pillar/types/assignableadapters.go
  pkg/pillar/types/assignableadapters_test.go
Labels: bug, stable

#4300 Use hard memory limit for EVE memory management.
  pkg/pillar/types/locationconsts.go
Labels: bug, stable

#4302 [12.0-stable] pkg/pillar: make ioBundleError deepcopy-able
  pkg/pillar/pubsub/publish.go
  pkg/pillar/pubsub/subscribe.go
  pkg/pillar/pubsub/util.go
  pkg/pillar/pubsub/util_test.go
  pkg/pillar/types/assignableadapters.go
  pkg/pillar/types/assignableadapters_test.go
Labels: bug

#4306 [12.0-stable] pillar: Use hard memory limit for EVE memory management.
  pkg/pillar/types/locationconsts.go
Labels: bug

#4305 [11.0-stable] pillar: Use hard memory limit for EVE memory management.
  pkg/pillar/types/locationconsts.go
Labels: bug

#4307 Do not try to decrypt empty wwan cipher data
  pkg/pillar/cmd/zedagent/parseconfig.go
Labels: bug

#4301 Allow EVE memory limits above 4GB.
  pkg/pillar/cmd/zedmanager/memorysizemgmt.go
  pkg/pillar/types/global.go
  pkg/pillar/types/global_test.go
Labels: bug, stable
