Repository lf-edge/eve, pull requests merged in 2024-08, with the labels that each got.

#4127 Move tpm2.OpenTPM call to CreateKey
  pkg/pillar/cmd/tpmmgr/tpmmgr.go
  pkg/pillar/evetpm/tpm.go
Labels: bug

#4130 domainmgr: config.enable.usb for new usb type
  pkg/pillar/cmd/domainmgr/domainmgr.go
  pkg/pillar/cmd/domainmgr/domainmgr_test.go
Labels: bug, stable

#4143 Make table index part of the IP-rule definition.
  pkg/pillar/dpcreconciler/linux.go
  pkg/pillar/dpcreconciler/linuxitems/srciprule.go
Labels: bug, stable

#4188 mini-yetus: a yetus you fall in love with
  Makefile
  tools/mini-yetus.sh
Labels: enhancement
