Repository lf-edge/eve, pull requests merged in 2024-10, with the labels that each got.

#4315 App-shared port without DNS server is not necessarily an issue
  pkg/pillar/cmd/zedagent/handlemetrics.go
  pkg/pillar/types/conntest.go
  pkg/pillar/types/dns.go
  pkg/pillar/types/dpc.go
  pkg/pillar/zedcloud/send.go
Labels: stable

#4321 Make sure ethernet interface is DOWN before renaming and changing MAC
  pkg/pillar/dpcreconciler/linuxitems/adapter.go
Labels: bug

#4323 Enhance scripts and Makefile targets for RC and LTS release support
  .github/workflows/assets.yml
  .github/workflows/publish.yml
  Makefile
  tools/lts-release.sh
  tools/rc-release.sh
Labels: stable

#4333 apparmor: allow SWTPM to receive term signal from vTPM
  pkg/apparmor/profiles/usr.bin.swtpm
  pkg/apparmor/profiles/usr.bin.vtpm
Labels: bug, stable

#4327 pillar: Fix OVMF binary file for ARM64
  pkg/pillar/cmd/zedmanager/handledomainmgr.go
Labels: bug, stable

#4331 memory-monitor: Fix log files clean up to prevent storage overflow.
  pkg/memory-monitor/src/monitor/memory-monitor-handler.sh
Labels: bug, stable

#4346 Set WType even for wireless ports without network config
  pkg/pillar/cmd/zedagent/parseconfig.go
  pkg/pillar/dpcmanager/verify.go
  pkg/pillar/dpcreconciler/linux.go
  pkg/pillar/types/dpc.go
Labels: bug, stable

#4362 Include ZFS in installer
  images/installer.yml.in
Labels: stable

#4372 memory-monitor: Restore output limit to 100 MB after refactor mistake.
  pkg/memory-monitor/src/monitor/memory-monitor-handler.sh
Labels: bug, stable

#4330 Wait for 15 seconds for the qmp listener
  pkg/pillar/hypervisor/kvm.go
  pkg/pillar/hypervisor/qmp.go
Labels: stable

#4376 memory-monitor: Improve resilience of handler to missing processes.
  pkg/memory-monitor/src/monitor/memory-monitor-handler.sh
Labels: stable

#4386 fix: update publish.yml to use the correct glob pattern
  .github/workflows/publish.yml
Labels: stable

#4397 Simplify assets.yml by using wildcards and loops
  .github/workflows/assets.yml
Labels: stable

#4393 fix: update regex in Makefile to correctly handle rc and lts tags
  Makefile
Labels: stable

#4395 Kernel update - Driver addition and BUG fix
  kernel-commits.mk
Labels: bug, stable
