Repository lf-edge/eve, pull requests merged in 2024-11, with the labels that each got.

#4409 pillar/devicenetwork: fix goroutine leak
  pkg/pillar/devicenetwork/dns.go
  pkg/pillar/devicenetwork/dns_test.go
  pkg/pillar/go.mod
  pkg/pillar/go.sum
  pkg/pillar/vendor/go.uber.org/goleak/.gitignore
  pkg/pillar/vendor/go.uber.org/goleak/.golangci.yml
  pkg/pillar/vendor/go.uber.org/goleak/CHANGELOG.md
  pkg/pillar/vendor/go.uber.org/goleak/LICENSE
  pkg/pillar/vendor/go.uber.org/goleak/Makefile
  pkg/pillar/vendor/go.uber.org/goleak/README.md
  pkg/pillar/vendor/go.uber.org/goleak/doc.go
  pkg/pillar/vendor/go.uber.org/goleak/internal/stack/doc.go
  pkg/pillar/vendor/go.uber.org/goleak/internal/stack/scan.go
  pkg/pillar/vendor/go.uber.org/goleak/internal/stack/stacks.go
  pkg/pillar/vendor/go.uber.org/goleak/leaks.go
  pkg/pillar/vendor/go.uber.org/goleak/options.go
  pkg/pillar/vendor/go.uber.org/goleak/testmain.go
  pkg/pillar/vendor/go.uber.org/goleak/tracestack_new.go
  pkg/pillar/vendor/modules.txt
Labels: bug, stable, go

#4422 Update liburing source URL to kernel.org
  pkg/xen-tools/Dockerfile
Labels: bug, dependencies

#4421 Fix app discovery endpoint
  pkg/pillar/cmd/msrv/msrv_test.go
  pkg/pillar/cmd/msrv/pubsub.go
Labels: bug, stable, go

#4432 uefi : fix broken build due to missing edk2 submodule
  pkg/uefi/Dockerfile
  pkg/uefi/edk2-patches/edk2-stable202408.01/0000-Add-Xen-spoofing-in-XenPlatformPei.patch
Labels: dependencies
