Repository lf-edge/eve, pull requests merged in 2025-08, with the labels that each got.

#5151 dpcreconciler: add rfkill dependency for WiFi adapters
  pkg/pillar/dpcreconciler/linux_test.go
  pkg/pillar/dpcreconciler/linuxitems/adapter.go
Labels: bug, stable

#5158 Added threshold to SATA devices for SMART metrics
  pkg/pillar/hardware/smart.go
  pkg/pillar/types/smarttypes.go
Labels: bug, stable

#5168 [13.4-stable] dpcreconciler: add rfkill dependency for WiFi adapters
  pkg/pillar/dpcreconciler/linux_test.go
  pkg/pillar/dpcreconciler/linuxitems/adapter.go
Labels: bug

#5166 [14.5-stable] Added threshold to SATA devices for SMART metrics
  pkg/pillar/hardware/smart.go
  pkg/pillar/types/smarttypes.go
Labels: bug

#5167 [14.5-stable] dpcreconciler: add rfkill dependency for WiFi adapters
  pkg/pillar/dpcreconciler/linux_test.go
  pkg/pillar/dpcreconciler/linuxitems/adapter.go
Labels: bug

#5185 pkg/mkrootfs-squash: improve compression
  pkg/mkrootfs-squash/make-rootfs
Labels: side-quest

#5195 kubevirt: cluster config deletion missing node drain/delete
  pkg/pillar/cmd/zedkube/clusterstatus.go
Labels: stable

#5194 Expand USB diag log collection
  pkg/pillar/scripts/device-steps.sh
Labels: stable
