Repository lf-edge/eve, pull requests merged in 2025-05, with the labels that each got.

#4789 Fix controllerCertsTask certificate fetch trigger logic
  pkg/pillar/cmd/zedagent/handlecertconfig.go
Labels: bug, stable

#4822 Handle WirelessType NOOP
  pkg/pillar/cmd/zedagent/parseconfig.go
Labels: bug

#4826 Avoid Repeatedly Clearing Bearers for Disabled Modems
  pkg/wwan/mmagent/agent.go
Labels: bug

#4825 Enforce always-on power mode for specific problematic PCI modems
  pkg/udev/etc/udev/rules.d/02-modem.rules
Labels: stable

#4854 Makefile: Remove duplicated targets
  Makefile
Labels: stable

#4847 Fix missing reboot on rollback without purge
  pkg/pillar/cmd/zedmanager/zedmanager.go
Labels: stable

#4864 fw: Fix build for arm64
  pkg/fw/Dockerfile
Labels: bug

#4865 Fix errors in Makefile
  Makefile
  kernel-version.mk
Labels: stable

#4827 Retry publishing ECC memory report if failure to send to controller
  pkg/pillar/cmd/zedagent/handlecertconfig.go
  pkg/pillar/cmd/zedagent/handleconfig.go
  pkg/pillar/cmd/zedagent/handlemetrics.go
  pkg/pillar/cmd/zedagent/parseconfig.go
Labels: bug, stable

#4871 Fix image .yq modifiers parsing
  Makefile
  images/modifiers/nvidia-jp5.yq
  images/modifiers/nvidia-jp6.yq
  kernel-version.mk
Labels: bug

#4879 Reapply "Makefile: Use Go builder container to build get-deps"
  Makefile
Labels: stable

#4881 github/workflows: Change arm64 build runner to Zededa Self hosted run…
  .github/workflows/build.yml
Labels: stable

#4885 be sure to include config.img/grub.cfg override in installer
  pkg/eve/installer/grub_installer.cfg
  pkg/eve/runme.sh
  pkg/mkimage-iso-efi/initrd.sh
  pkg/mkimage-iso-efi/make-efi
Labels: stable
