Repository lf-edge/eve, pull requests merged in 2025-06, with the labels that each got.

#4925 Avoid reevaluation of Linuxkit target
  Makefile
Labels: enhancement

#4939 Fix broken run-* targets for dirty builds
  Makefile
Labels: bug

#4957 [14.5-stable] Remove replace directive for pillar from mmagent's go.mod
  pkg/wwan/mmagent/go.mod
  pkg/wwan/mmagent/go.sum
  pkg/wwan/mmagent/vendor/github.com/lf-edge/eve/pkg/pillar/LICENSE
  pkg/wwan/mmagent/vendor/github.com/lf-edge/eve/pkg/pillar/evetpm/encryptdecypt.go
  pkg/wwan/mmagent/vendor/golang.org/x/net/html/atom/table.go
  pkg/wwan/mmagent/vendor/golang.org/x/net/html/parse.go
  pkg/wwan/mmagent/vendor/golang.org/x/net/html/token.go
  pkg/wwan/mmagent/vendor/golang.org/x/net/http2/frame.go
  pkg/wwan/mmagent/vendor/golang.org/x/net/http2/server.go
  pkg/wwan/mmagent/vendor/golang.org/x/sync/errgroup/errgroup.go
  pkg/wwan/mmagent/vendor/golang.org/x/sync/errgroup/go120.go
  pkg/wwan/mmagent/vendor/golang.org/x/sync/errgroup/pre_go120.go
  pkg/wwan/mmagent/vendor/golang.org/x/text/language/parse.go
  pkg/wwan/mmagent/vendor/modules.txt
Labels: dependencies

#4956 Remove replace directive for pillar from mmagent's go.mod
  pkg/wwan/mmagent/go.mod
  pkg/wwan/mmagent/go.sum
  pkg/wwan/mmagent/vendor/github.com/lf-edge/eve/pkg/pillar/LICENSE
  pkg/wwan/mmagent/vendor/github.com/lf-edge/eve/pkg/pillar/evetpm/encryptdecypt.go
  pkg/wwan/mmagent/vendor/github.com/lf-edge/eve/pkg/pillar/types/ledmanagertypes.go
  pkg/wwan/mmagent/vendor/modules.txt
Labels: dependencies, stable

#4975 mmagent: apply errIsUseless logic to LTE attach config errors
  pkg/wwan/mmagent/mmdbus/client.go
Labels: stable

#4995 Update Hailo TPU FW to 4.21.0
  pkg/fw/Dockerfile
Labels: enhancement, stable

#5007 Kernel update - [amd64-generic]
  kernel-commits.mk
Labels: enhancement, stable
