Repository lf-edge/eve, pull requests merged in 2025-03, with the labels that each got.

#4662 tools: Fix tag for eve-mkimage-iso-efi
  tools/makeiso.sh
Labels: stable

#4670 docs: Fix security warnings pointed by dependabot
  docs/mkdocs/prepare_mkdocs.py
  docs/mkdocs/requirements.txt
Labels: security

#4674 Fix flow-logging config removal
  pkg/pillar/nireconciler/linux_acl.go
Labels: bug

#4675 Always enable bridge iptables for kubernetes networking
  pkg/pillar/nireconciler/linux_config.go
Labels: bug, stable
