Repository lf-edge/eve, pull requests merged in 2025-01, with the labels that each got.

#4504 Kernel update - [amd64-generic, arm64-generic, arm64-nvidia, arm64-generic, arm64-generic, arm64-generic]
  kernel-commits.mk
Labels: stable

#4514 Kernel update - [arm64-generic] (to fix TPM on RPi 4B)
  kernel-commits.mk
Labels: stable

#4522 pillar: Refine log messages for threshold-based timing warnings.
  pkg/pillar/pubsub/checkmaxtime.go
Labels: stable

#4524 [13.4-stable] pillar: Refine log messages for threshold-based timing warnings.
  pkg/pillar/pubsub/checkmaxtime.go
Labels: stable

#4525 [12.0-stable] pillar: Refine log messages for threshold-based timing warnings.
  pkg/pillar/pubsub/checkmaxtime.go
Labels: stable

#4529 Fix deleted app is displayed in halted state
  pkg/pillar/cmd/monitor/messages.go
  pkg/pillar/cmd/monitor/subscriptions.go
Labels: stable

#4558 [13.4-stable] Include proper iso volume label when running docker run eve installer_iso
  pkg/eve/runme.sh
Labels: bug, stable

#4563 Avoid nil dereference in baseosmgr
  pkg/pillar/cmd/baseosmgr/handledownload.go
Labels: stable

#4571 Add missing FW package to installer
  images/installer.yml.in
Labels: stable

#4561 [GH actions] Add OSV-Scanner GitHub Actions workflow for vulnerability scanning
  .github/workflows/osv-scanner.yml
Labels: enhancement

#4572 [13.4-stable] fix: Updated the eden.yml to use the new upload actions
  .github/workflows/eden.yml
Labels: stable
