Repository lf-edge/eve, pull requests merged in 2025-07, with the labels that each got.

#5037 Fix 'unauthenticated pull rate limit reached' problem
  Makefile
Labels: bug

#5035 [11.0-stable] Avoid endless loop in DPCManager.runVerify when we get RemoteTemporaryFailure
  pkg/pillar/dpcmanager/dpcmanager_test.go
  pkg/pillar/dpcmanager/verify.go
Labels: bug

#5044 Upgrade Linuxkit to 1.7.0
  Makefile
Labels: bug, stable

#5036 Move LastResort DPC handling fully into DPCManager
  pkg/pillar/cmd/nim/nim.go
  pkg/pillar/dpcmanager/dpc.go
  pkg/pillar/dpcmanager/dpcmanager.go
  pkg/pillar/dpcmanager/dpcmanager_test.go
  pkg/pillar/dpcmanager/lastresort.go
  pkg/pillar/netmonitor/mock.go
Labels: bug, stable

#5031 Handle error IsAlreadyExists
  pkg/pillar/hypervisor/kubevirt.go
Labels: stable

#5042 vault: Check policyID exist before indexing
  pkg/pillar/vault/handler_ext4.go
Labels: bug, stable

#5047 Introduce Air-gap mode
  docs/CONFIG-PROPERTIES.md
  docs/DEVICE-CONNECTIVITY.md
  pkg/pillar/cmd/diag/diag.go
  pkg/pillar/cmd/loguploader/loguploader.go
  pkg/pillar/cmd/nim/nim.go
  pkg/pillar/cmd/zedagent/attesttask.go
  pkg/pillar/cmd/zedagent/handlecertconfig.go
  pkg/pillar/cmd/zedagent/handleconfig.go
  pkg/pillar/cmd/zedagent/handlemetrics.go
  pkg/pillar/cmd/zedagent/handlenetworkinstance.go
  pkg/pillar/cmd/zedagent/parseconfig.go
  pkg/pillar/cmd/zedagent/zedagent.go
  pkg/pillar/conntester/conntester.go
  pkg/pillar/conntester/controller.go
  pkg/pillar/conntester/mock.go
  pkg/pillar/controllerconn/deferred.go
  pkg/pillar/controllerconn/send.go
  pkg/pillar/controllerconn/send_test.go
  pkg/pillar/dpcmanager/dpcmanager.go
  pkg/pillar/dpcmanager/verify.go
  pkg/pillar/types/global.go
  pkg/pillar/types/global_test.go
  pkg/pillar/types/zedagenttypes.go
Labels: enhancement

#5053 Update Eden to version 1.0.5.
  .github/workflows/eden-trusted.yml
Labels: stable

#5030 Fixes in the S.M.A.R.T. report
  pkg/pillar/hardware/smart.go
  pkg/pillar/types/smarttypes.go
Labels: bug, stable

#5068 Update Eden to 1.0.6 that fixes Dockerhub 429 error
  .github/workflows/eden-trusted.yml
Labels: bug, stable

#5065 Fix image size for kubevirt 'docker run <img> installer_raw'
  pkg/eve/runme.sh
Labels: bug, stable

#5060 Cleanup Replica sets only in single node mode
  pkg/pillar/cmd/domainmgr/domainmgr.go
  pkg/pillar/kubeapi/kubeapi.go
  pkg/pillar/kubeapi/nokube.go
  pkg/pillar/types/locationconsts.go
Labels: stable

#5086 Kernel update - Add HWE kernel
  kernel-commits.mk
Labels: main-quest

#5102 Update rust version for pkg/monitor to 1.85.1-1
  pkg/monitor/Dockerfile
Labels: stable, main-quest

#5061 Return unknown error if k3s is not reachable
  pkg/pillar/hypervisor/kubevirt.go
Labels: stable

#5113 Follow up PR for PR#5111
  Makefile
Labels: bug, main-quest

#5101 Integrate monitor v0.5.0
  pkg/monitor/Dockerfile
Labels: stable, main-quest

#5124 github/workflows: Switch to arm64 runners
  .github/workflows/build.yml
  .github/workflows/publish.yml
Labels: stable

#5147 spec.sh: fix modem assigngrp
  pkg/debug/spec.sh
  pkg/installer/spec.sh
Labels: bug, stable
