Repository lf-edge/eve, pull requests merged in 2025-02, with the labels that each got.

#4559 Fix vm unknown state
  pkg/pillar/cmd/domainmgr/domainmgr.go
  pkg/pillar/containerd/containerd.go
  pkg/pillar/hypervisor/containerd.go
Labels: bug, stable

#4596 stat st_blocks block size read from DEV_BSIZE
  pkg/pillar/diskmetrics/usage.go
  pkg/pillar/diskmetrics/usage_test.go
Labels: stable

#4605 Wait for root device inside the initrd script for ISO images
  pkg/mkimage-iso-efi/initrd.sh
Labels: stable

#4608 eve: Fix override configuration for ISO image generator
  pkg/eve/runme.sh
Labels: stable

#4614 Do not check tpm sanity if it is not enabled
  pkg/pillar/cmd/tpmmgr/tpmmgr.go
Labels: bug

#4628 eve: installer: Add rootwait by default
  pkg/eve/installer/grub_installer.cfg
Labels: stable
