Repository lf-edge/eve, pull requests merged in 2025-09, with the labels that each got.

#5198 implement DhcpOptionsIgnore for IP, DNS, and Gateway
  docs/DEVICE-CONNECTIVITY.md
  pkg/pillar/cmd/diag/diag.go
  pkg/pillar/cmd/zedagent/handlemetrics.go
  pkg/pillar/cmd/zedagent/parseconfig.go
  pkg/pillar/cmd/zedagent/parseconfig_test.go
  pkg/pillar/cmd/zedagent/reportinfo.go
  pkg/pillar/cmd/zedrouter/networkinstance.go
  pkg/pillar/dpcmanager/dns.go
  pkg/pillar/dpcmanager/dpcmanager_test.go
  pkg/pillar/dpcreconciler/genericitems/dhcpcd.go
  pkg/pillar/dpcreconciler/genericitems/dhcpcd_test.go
  pkg/pillar/dpcreconciler/linux.go
  pkg/pillar/dpcreconciler/linux_test.go
  pkg/pillar/netmonitor/linux.go
  pkg/pillar/netmonitor/linux_test.go
  pkg/pillar/netmonitor/netmonitor.go
  pkg/pillar/nireconciler/linux_acl.go
  pkg/pillar/nireconciler/linux_config.go
  pkg/pillar/nireconciler/linux_currentstate.go
  pkg/pillar/nireconciler/linux_test.go
  pkg/pillar/nireconciler/nireconciler.go
  pkg/pillar/scripts/device-steps.sh
  pkg/pillar/types/dns.go
  pkg/pillar/types/dpc.go
  pkg/pillar/types/zedroutertypes.go
  pkg/pillar/utils/common.go
  pkg/pillar/utils/netutils/hostnameorip.go
  pkg/pillar/utils/netutils/ip.go
Labels: enhancement, main-quest

#5200 Integrate monitor-rs version v0.6.0
  pkg/monitor/Dockerfile
Labels: bug, stable

#5232 Kernel update - [amd64-generic]
  kernel-commits.mk
Labels: new feature

#5191 zedagent: refactor LPS handling into LocalCmdAgent component
  docs/LPS.md
  docs/mkdocs/mkdocs.yml
  pkg/pillar/cmd/baseosmgr/forcefallback.go
  pkg/pillar/cmd/monitor/messages.go
  pkg/pillar/cmd/zedagent/handleProfile.go
  pkg/pillar/cmd/zedagent/handlecertconfig.go
  pkg/pillar/cmd/zedagent/handleconfig.go
  pkg/pillar/cmd/zedagent/handleedgenodecluster.go
  pkg/pillar/cmd/zedagent/handlelocation.go
  pkg/pillar/cmd/zedagent/handlelookupparam.go
  pkg/pillar/cmd/zedagent/handlemetrics.go
  pkg/pillar/cmd/zedagent/handlenetworkinstance.go
  pkg/pillar/cmd/zedagent/handlevolume.go
  pkg/pillar/cmd/zedagent/localcommand.go
  pkg/pillar/cmd/zedagent/localinfo.go
  pkg/pillar/cmd/zedagent/parseconfig.go
  pkg/pillar/cmd/zedagent/radiosilence.go
  pkg/pillar/cmd/zedagent/reportinfo.go
  pkg/pillar/cmd/zedagent/validate.go
  pkg/pillar/cmd/zedagent/zedagent.go
  pkg/pillar/docs/zedagent.md
  pkg/pillar/localcommand/agent.go
  pkg/pillar/localcommand/appinfo.go
  pkg/pillar/localcommand/devinfo.go
  pkg/pillar/localcommand/location.go
  pkg/pillar/localcommand/profile.go
  pkg/pillar/localcommand/radio.go
  pkg/pillar/types/errortime.go
  pkg/pillar/types/locationconsts.go
  pkg/pillar/types/wwan.go
  pkg/pillar/types/zedagenttypes.go
  pkg/pillar/types/zedmanagertypes.go
  pkg/pillar/types/zedroutertypes.go
  pkg/pillar/utils/persist/checkpoint.go
Labels: main-quest

#5169 kubevirt: fix BaseOs Update defer check, ensure drain is requested
  pkg/pillar/cmd/baseosmgr/handlebaseos.go
Labels: bug, stable

#5240 reportinfo: fix copy&paste error
  pkg/pillar/cmd/zedagent/parseconfig.go
  pkg/pillar/cmd/zedagent/reportinfo.go
Labels: bug, stable

#5228 pillar/Makefile: only run lkt when build-args need
  pkg/pillar/Makefile
Labels: side-quest

#5246 Create bridge between VLAN parent port and its sub-interfaces
  docs/DEVICE-CONNECTIVITY.md
  docs/images/eve-vlans-and-lags.png
  docs/images/eve-vlans-and-lags.xml
  pkg/pillar/cmd/zedrouter/networkinstance.go
  pkg/pillar/dpcmanager/dns.go
  pkg/pillar/dpcreconciler/genericitems/netio.go
  pkg/pillar/dpcreconciler/linux.go
  pkg/pillar/dpcreconciler/linux_test.go
  pkg/pillar/dpcreconciler/linuxitems/adapter.go
  pkg/pillar/dpcreconciler/linuxitems/bond.go
  pkg/pillar/dpcreconciler/linuxitems/vlan.go
  pkg/pillar/netmonitor/linux.go
  pkg/pillar/netmonitor/netmonitor.go
  pkg/pillar/nireconciler/genericitems/port.go
  pkg/pillar/nireconciler/linux_config.go
  pkg/pillar/nireconciler/linux_currentstate.go
  pkg/pillar/nireconciler/linux_reconciler.go
  pkg/pillar/nireconciler/linux_test.go
  pkg/pillar/nireconciler/linuxitems/bpduguard.go
  pkg/pillar/nireconciler/linuxitems/bridge.go
  pkg/pillar/nireconciler/linuxitems/bridgeport.go
  pkg/pillar/nireconciler/linuxitems/typenames.go
  pkg/pillar/nireconciler/linuxitems/vif.go
  pkg/pillar/nireconciler/linuxitems/vlanport.go
  pkg/pillar/nireconciler/linuxitems/vlansubif.go
  pkg/pillar/nireconciler/nireconciler.go
  pkg/pillar/types/dpc.go
Labels: enhancement, stable, main-quest

#5258 diag: make Internet probe endpoints configurable
  docs/CONFIG-PROPERTIES.md
  docs/DEVICE-CONNECTIVITY.md
  pkg/pillar/cmd/diag/diag.go
  pkg/pillar/cmd/nim/nim.go
  pkg/pillar/conntester/controller.go
  pkg/pillar/types/global.go
  pkg/pillar/types/global_test.go
Labels: enhancement, stable, main-quest

#5263 Fix riscv debug build
  pkg/debug/Dockerfile
Labels: stable

#5270 diag: restore setting of ctx.globalConfig in handleGlobalConfigImpl
  pkg/pillar/cmd/diag/diag.go
Labels: bug
